receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:1972
      http:
        endpoint: 0.0.0.0:1973
  # Host metrics
  hostmetrics:
    collection_interval: 60s
    scrapers:
      cpu: {}
      disk: {}
      load: {}
      filesystem: {}
      memory: {}
      network: {}
      paging: {}
      process:
        mute_process_name_error: true
        mute_process_exe_error: true
        mute_process_io_error: true
      processes: {}
  # prometheus exporter
  
#  prometheus:
#    config:
#      global:
#        scrape_interval: 60s
#      scrape_configs:
#        - job_name: otel-collector-binary
#          static_configs:
#            - targets:
           # - localhost:8888 # Uncomment to scrape Collector's own metrics
  # SysLogs
  syslog:
    tcp:
      listen_address: '0.0.0.0:54527'
    protocol: rfc3164
    location: UTC
    operators:
      - type: move
        from: attributes.message
        to: body
  # Journald Logs
  journald:
    directory: /var/log/journal
    start_at: end

processors:
  resource/host_identity:
    attributes:
      - key: host.name
        value: EKS_AGENT-vm-linux   # CHANGE per machine
        action: upsert
      - key: deployment.environment
        value: production # CHANGE per environment
        action: upsert
  batch:
    send_batch_size: 1000
    timeout: 10s
  # Ref: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/resourcedetectionprocessor/README.md
  resourcedetection:
    detectors: [env] # Before system detector, include ec2 for AWS, gcp for GCP and azure for Azure.
    # Using OTEL_RESOURCE_ATTRIBUTES envvar, env detector adds custom labels.
    timeout: 2s
    system:
      hostname_sources: [os] # alternatively, use [dns,os] for setting FQDN as host.name and os as fallback

exporters:
  otlp:
    endpoint: 172.31.0.155:1972
    tls:
      insecure: true

  debug:
    verbosity: normal

extensions:
  health_check: {}
  zpages: {}

service:
  telemetry:
    metrics:
      level: basic
  extensions: [health_check, zpages]
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [resourcedetection, resource/host_identity, batch]
      exporters: [otlp]
   
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp, syslog, journald]
      processors: [resourcedetection, resource/host_identity, batch]
      exporters: [otlp]
    
## old 4317 = 1972
## old 4318 = 1973
